<template>
  <div>
    <div class="">
      <small v-if="verifiedEmail" class="text-danger text-left mt-4">* you can only set one method</small>
      <hr>
      <div v-if="verifiedEmail" class="d-flex bd-highlight text-white">
        <div :class="'p-2 flex-fill rounded-pill pointer '+(emailIsSelected ? 'bg-theme': 'bg-theme-secondary')"
             @click="showMethods(0)">
          Email 2FA
        </div>
        <div :class="'p-2 flex-fill rounded-pill pointer '+(emailIsSelected ? 'bg-theme-secondary' :  'bg-theme')"
             @click="showMethods(1)">
          Google Authenticator
        </div>
      </div>
      <div v-else>
        <h5 class="text-danger text-center">You have to verify your email first to enable 2FA</h5>
      </div>
      <hr>
    </div>
    <div v-if="verifiedEmail">
      <div v-if="emailIsSelected">
        <div class="text-left">
          <div v-show="emailErr" class="text-danger text-break">Verify that Google authenticator 2FA is disabled then
            try again
          </div>
          <span style="font-size: large">Enable email authentication: </span>
          <label class="switch">
            <input v-model="emailChecked" :disabled="loading || authAppChecked" class="mt-2" type="checkbox"
                   @click="handleEmail2FA">
            <span class="slider round"></span>
          </label>
        </div>
      </div>
      <div v-if="!emailIsSelected">
        <div class="text-left">
          <div v-show="appErr" class="text-danger text-break">{{ message }}</div>

          <span v-if="authAppChecked">
          <span  style="font-size: large">Enable Google authenticator: </span>
          <label class="switch">
            <input v-model="authAppChecked" :disabled="loading || emailChecked" class="mt-2" type="checkbox"
                   @click="deactivateApp2FA">
            <span class="slider round"></span>
          </label>
          </span>

          <div v-else-if="!authAppChecked && !emailChecked">
            <span style="font-size: large">Enable Google authenticator: </span>
            <button :disabled="loading" class="btn btn-theme" @click="handleApp2FA">
              <span v-show="loading" class="spinner-border spinner-border-sm"></span>
              <span>Generate key</span>
            </button>

            <div v-if="hasToken" class="text-center py-2">
              <p><span class="font-weight-bold">Step 1: </span>Scan the code below with your phone</p>
              <qrcode-vue :value="qrCode.value" :size="qrCode.size" />
              <div class="separator my-1 col-8 col-md-10 mx-auto">or</div>
              <textarea id="tokenArea" rows="2" v-model="token" readonly class="form-control col-md-8 col-7 mx-auto my-2"></textarea>
              <button class="btn btn-sm btn-primary btn-theme" @click="copy">Copy</button>
              <span v-if="!copied"> and paste the code above in your authenticator app.</span>
              <span v-else> copied!.</span>

              <p class="mt-5"><span class="font-weight-bold">Step 2: </span>Enter the code generated by your authenticator app below</p>
              <form @submit.prevent="verifyTOTP">
                <input class="form-control col-md-6 col-6 mx-auto m-1" type="number" min="6" v-model="appToken" />
                <p class="text-danger" v-if="error">{{error}}</p>
                <button :disabled="loading1" class="btn btn-sm btn-outline-theme rounded-pill" type="submit">
                  <span v-show="loading1" class="spinner-border spinner-border-sm"></span>
                  <span>Submit</span>
                </button>
              </form>
            </div>
          </div>

          <div v-else>
          <span  style="font-size: large">Enable Google authenticator: </span>
          <label class="switch">
            <input v-model="authAppChecked" :disabled="loading || emailChecked" class="mt-2" type="checkbox"
                   @click="deactivateApp2FA">
            <span class="slider round"></span>
          </label>
          </div>

        </div>
      </div>
    </div>
  </div>
</template>

<script>
import AuthService from '../../../../services/authentication/auth.service.js';
import QrcodeVue from 'qrcode.vue'

export default {
  name: "TwoFA",
  components: {
    QrcodeVue,
  },
  data() {
    return {
      qrCode: {
        value: '',
        size: 200
      },
      method: 0,
      loading: false,
      loading1: false,
      emailErr: false,
      emailChecked: false,
      authAppChecked: false,
      appErr: false,
      message: "",
      hasToken: null,
      token: null,
      appToken: null,
      error: null,
      copied: null,
    }
  },
  methods: {
    showMethods(m) {
      this.method = m;
    },
    handleEmail2FA() {
      this.emailErr = false;

      if (this.the2FAtype === 'EMAIL') {
        this.loading = true;
        this.$store.dispatch('profile/deActivateEmail2FA').then(
          res => {
            this.loading = false;
            this.emailSwitch = false;
          },
          err => {
            this.loading = false;
            this.emailSwitch = true;
          }
        );
      } else if (this.the2FAtype === '') {
        this.loading = true;
        this.$store.dispatch('profile/activateEmail2FA').then(
          res => {
            this.loading = false;
            this.emailSwitch = true;
          },
          err => {
            this.emailErr = true;
            this.emailSwitch = false;
            this.loading = false;
          }
        );
      } else {
        this.emailErr = true;
      }
    },
    handleApp2FA() {
      this.loading = true;
      this.message = '';
      this.appErr = false;
      this.token = null;
      this.hasToken = null;

      AuthService.createTOTP2FA().then(
        res => {
          this.hasToken = true;
          this.loading = false;
          this.token = res.data.data.Key;
          this.qrCode.value = res.data.data.url;
        },
        error => {
          this.appErr = true;
          if (error.response) {
            this.message = error.response.data.message;
          } else if (error.request) {
            // The request was made but no response was received
            this.message = "Check your internet connection"
          } else {
            this.message = "An error occurred"
          }
          this.loading = false;
        }
      );
    },
    verifyTOTP(){
      this.loading1 = true;
      this.$store.dispatch('profile/verifyTOTP2FA',this.appToken).then(
        res=>{
          this.loading1 = false;
          this.appSwitch = true;
        },
        error=>{
          if (error.response) {
            this.error = error.response.data.message;
          } else if (error.request) {
            // The request was made but no response was received
            this.error = "Check your internet connection"
          } else {
            this.error = "An error occurred"
          }
          this.loading1 = false;
        }
      );
    },
    deactivateApp2FA() {
      this.$store.dispatch('profile/deActivateApp2FA').then(
        res => {
          this.appSwitch = false;
          this.hasToken = false;
          this.token = '';
          this.qrCode.value = '';
        },
        error=>{
          if (error.response) {
            this.error = error.response.data.message;
          } else if (error.request) {
            // The request was made but no response was received
            this.error = "Check your internet connection"
          } else {
            this.error = "An error occurred"
          }
          this.loading = false;
        }
      );
    },
    copy () {
      let tokenCopy = document.querySelector('#tokenArea');
      tokenCopy.setAttribute('type', 'text');
      tokenCopy.select();
      document.execCommand('copy');
      /* unselect the range */
      tokenCopy.setAttribute('type', 'hidden');
      window.getSelection().removeAllRanges();

      this.copied = true;
      setTimeout(function(){
        this.copied = false;
      }.bind(this), 3000);
    },
  },
  created() {
    this.emailChecked = this.the2FAtype === 'EMAIL';
    this.authAppChecked = this.the2FAtype === 'AUTHENTICATOR';
  },
  computed: {
    emailIsSelected: function () {
      return !!!this.method;
    },
    verifiedEmail: function () {
      return this.$store.getters['profile/emailVerified'];
    },
    the2FAtype: function () {
      return this.$store.getters['profile/the2FA'];
    },
    emailSwitch: {
      get: function () {
        return this.emailChecked;
      },
      set: function (v) {
        this.emailChecked = v;
      }
    },
    appSwitch: {
      get: function () {
        return this.authAppChecked;
      },
      set: function (v) {
        this.authAppChecked = v;
      }
    }
  }
}
</script>

<style scoped>
textarea{
  resize:none;
}

.separator {
  display: flex;
  align-items: center;
  text-align: center;
  color: #9e6fd1;
}
.separator::before, .separator::after {
  content: '';
  flex: 1;
  border-bottom: 1px solid #9e6fd1;
}
.separator::before {
  margin-right: .25em;
}
.separator::after {
  margin-left: .25em;
}

.pointer {
  cursor: pointer;
}

.switch {
  position: relative;
  display: inline-block;
  width: 60px;
  height: 34px;
}

.switch input {
  opacity: 0;
  width: 0;
  height: 0;
}

.slider {
  position: absolute;
  cursor: pointer;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background-color: #ccc;
  -webkit-transition: .4s;
  transition: .4s;
}

.slider:before {
  position: absolute;
  content: "";
  height: 26px;
  width: 26px;
  left: 4px;
  bottom: 4px;
  background-color: white;
  -webkit-transition: .4s;
  transition: .4s;
}

input:checked + .slider {
  background-color: #9e6fd1;
}

input:focus + .slider {
  box-shadow: 0 0 1px #9e6fd1;
}

input:checked + .slider:before {
  -webkit-transform: translateX(26px);
  -ms-transform: translateX(26px);
  transform: translateX(26px);
}

/* Rounded sliders */
.slider.round {
  border-radius: 34px;
}

.slider.round:before {
  border-radius: 50%;
}
</style>
